format = """
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

add_newline = true

[directory]
format = '[$path]($style) '
style = "bold cyan"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold purple)"
#success_symbol = "[❯](green)"
#error_symbol = "[❯](red)"
#vimcmd_symbol = "[❮](purple)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
#stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[($virtualenv )]($style)"
style = "bright-black"

[kubernetes]
format = '([\[$context\]]($style) )'
style = "bold bright-white"
disabled = false

