syntax on

set nowrap

" Use tabs only
set tabstop=4
set softtabstop=0
set expandtab
set shiftwidth=4

set nu
set autoindent
set smartindent
set cursorline
set relativenumber

" Default is 4000ms
set updatetime=750

" Copy to main clipboard
set clipboard+=unnamedplus

" Some color hack
if &term =~ '256-color'
	set t_ut=
endif

" Install vim-plug if it's not installed
if empty(glob('~/.vim/autoload/plug.vim'))
	silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
				\ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

"Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'ap/vim-css-color'
Plug 'itchyny/lightline.vim'
Plug 'itchyny/vim-gitbranch'
Plug 'udalov/kotlin-vim'
"Plug 'jiangmiao/auto-pairs'
Plug 'cormacrelf/vim-colors-github'
Plug 'rakr/vim-two-firewatch'
Plug 'tpope/vim-abolish'
"Plug 'octol/vim-cpp-enhanced-highlight'

Plug 'jvirtanen/vim-hcl'
Plug 'bfrg/vim-cpp-modern'
" Initialize plugin system
call plug#end()

" fzf search
map ; :Files<CR>

" lightline config
" see https://github.com/itchyny/lightline.vim
set laststatus=2
set noshowmode
let g:lightline = {
	\ 'colorscheme' : 'cold',
	\ 'active' : {
	\	'left' : [ ['mode', 'paste'],
	\		   [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
	\ },
	\ 'component_function' : {
	\ 	'gitbranch': 'gitbranch#name'
	\ },
	\ }

" This fixes color issues in tmux for example
set t_8f=[38;2;%lu;%lu;%lum
set t_8b=[48;2;%lu;%lu;%lum


" True colors set
set t_Co=256
set termguicolors

" Set the colorscheme
"set background=light
"colo two-firewatch
colo cold

" Set the background to transparent (match terminal)
hi! Normal guibg=NONE ctermbg=NONE
hi! NonTest guibg=NONE ctermbg=NONE

" To bulk uppercase files
" \ls | vim -
" :%s/.*/\="mv -i ".submatch(0)." ".substitute(submatch(0), "\\<.", "\\u&",
" "")/g
" :w !sh

" Formating etc.
set formatoptions+=r
set formatoptions+=c
set formatoptions+=o
set foldmethod=syntax

au BufNewFile,BufRead,BufReadPost *.frag,*.vert,*.fp,*.vp,*.glsl,*.rchit,*.rgen,*.rmiss,*.comp,*.shader set syntax=c

autocmd BufWritePre * :%s/\s\+$//e
" autocmd BufWritePre * silent $put _ | $;?\(^\s*$\)\@!?+1,$d

" Unfold on open
augroup OpenAllFoldsOnFileOpen
	autocmd!
	autocmd BufRead * normal zR
augroup END

" syntax based on ext
augroup terraform_syntax
    au!
    autocmd BufNewFile,BufRead *.tf set syntax=hcl
    autocmd BufNewFile,BufRead *.tf set shiftwidth=2
    autocmd BufNewFile,BufRead *.sh set shiftwidth=2
augroup END

"imap jk <ESC>

" No cheating
" Only use hjkl
inoremap <Up>    <Nop>
inoremap <Down>  <Nop>
inoremap <Right> <Nop>
inoremap <Left>  <Nop>

noremap <Up>    <Nop>
noremap <Down>  <Nop>
noremap <Right> <Nop>
noremap <Left>  <Nop>
