syntax on

set nowrap

" Use tabs only
set tabstop=4
set softtabstop=0 
set noexpandtab
set shiftwidth=4

set nu
set autoindent
set smartindent
set cursorline

" Default is 4000ms
set updatetime=750 

" Copy to main clipboard
set clipboard=unnamedplus

" Some color hack
if &term =~ '256-color'
	set t_ut=
endif

" Install vim-plug if it's not installed
if empty(glob('~/.vim/autoload/plug.vim'))
	silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
				\ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'ap/vim-css-color'
Plug 'itchyny/lightline.vim'
Plug 'itchyny/vim-gitbranch'
"Plug 'octol/vim-cpp-enhanced-highlight'

" Initialize plugin system
call plug#end()

" lightline config
" see https://github.com/itchyny/lightline.vim
set laststatus=2
set noshowmode
let g:lightline = {
	\ 'colorscheme' : 'cold',
	\ 'active' : {
	\	'left' : [ ['mode', 'paste'],
	\		   [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
	\ },
	\ 'component_function' : {
	\ 	'gitbranch': 'gitbranch#name'
	\ },
	\ }

" This fixes color issues in tmux for example
set t_8f=[38;2;%lu;%lu;%lum
set t_8b=[48;2;%lu;%lu;%lum

" Set the colorscheme
colorscheme cold

" True colors set
set t_Co=256
set termguicolors

" Set the background to transparent (match terminal)
"hi! Normal guibg=NONE ctermbg=NONE
"hi! NonTest guibg=NONE ctermbg=NONE

" To bulk uppercase files
" \ls | vim -
" :%s/.*/\="mv -i ".submatch(0)." ".substitute(submatch(0), "\\<.", "\\u&",
" "")/g
" :w !sh

" Formating etc.
set formatoptions+=r
set formatoptions+=c
set formatoptions+=o
set foldmethod=syntax

" Unfold on open
augroup OpenAllFoldsOnFileOpen
	autocmd!
	autocmd BufRead * normal zR
augroup END

imap jk <ESC>

" No cheating 
" Only use hjkl
inoremap <Up>    <Nop>
inoremap <Down>  <Nop>
inoremap <Right> <Nop>
inoremap <Left>  <Nop>

noremap <Up>    <Nop>
noremap <Down>  <Nop>
noremap <Right> <Nop>
noremap <Left>  <Nop>

